
OmnirobotEnv-v0:
  # Base path to SRL log folder
  # log_folder: srl_zoo/logs/Omnibot_random_simple/
  log_folder: srl_zoo/logs/omnirobot_simulator/
  srl_combination: 19-08-14_11h09_58_custom_cnn_ST_DIM200_autoencoder_inverse/srl_model.pth
  

